#!/usr/bin/env bash

limits=(1000 10000 50000 100000)

outfile=$1
iterations=$2

echo "file,n,code,user,sys,maxrss" > $outfile || exit 1

run() {
  for n in ${limits[@]}; do
    for i in $(eval echo "{1..$iterations}"); do
      echo "${1} /dev/null ${n}"
      \time --output=$outfile --append --format="${1},${n},%x,%U,%S,%M" $1 /dev/null $n
    done
  done
}

commands=(
  "py/main_tuple.py"
  "py/main_dict.py"
  "py/main_csv_dict.py"
  "py/main_csv_dataclass.py"
  "js/main_array.js"
  "js/main_object.js"
  "js/main_csv.js"
  "rs/target/release/fs_tuple"
  "rs/target/release/fs_struct"
  "rs/target/release/csv_serde"
)

for command in ${commands[@]}; do
  run $command
done
